#!/usr/bin/env python3
"""Regenerate share/cursors.toml from an upstream Bibata_Cursor checkout.

Bibata ships its shape metadata (hotspots, X11 aliases, animation delays) in
`configs/normal/x.build.toml`, keyed to the rendered PNG names. omarchy-cursor-dye
works straight from the SVG sources instead, so this script distills that build
config into a small, stable spec we vendor and read at runtime.

Usage:
    dev/gen-cursors-spec.py /path/to/Bibata_Cursor > share/cursors.toml

Run it again whenever Bibata bumps its shape set. The output is deterministic.
"""

from __future__ import annotations

import sys
import tomllib
from pathlib import Path

CANVAS = 256  # Bibata SVG viewBox is 0 0 256 256; hotspots below are in these units.


def main() -> int:
    if len(sys.argv) != 2:
        sys.exit(__doc__)

    bibata = Path(sys.argv[1])
    build_toml = bibata / "configs" / "normal" / "x.build.toml"
    svg_dir = bibata / "svg" / "modern"

    if not build_toml.is_file():
        sys.exit(f"not a Bibata checkout: {build_toml} missing")

    data = tomllib.loads(build_toml.read_text())
    cursors = data["cursors"]
    fallback = cursors.get("fallback_settings", {})
    fb_x = fallback.get("x_hotspot", CANVAS // 2)
    fb_y = fallback.get("y_hotspot", CANVAS // 2)
    fb_delay = fallback.get("x11_delay", 40)

    out: list[str] = []
    out.append("# Generated by dev/gen-cursors-spec.py from Bibata_Cursor.")
    out.append("# Hotspots are fractions of the cursor box (Bibata canvas is 256px).")
    out.append("# Do not edit by hand; rerun the generator instead.")
    out.append("")

    shapes = []
    for key, cur in sorted(cursors.items()):
        if key == "fallback_settings":
            continue

        png = cur.get("png", f"{key}.png")
        name = cur.get("x11_name", key)

        if png.endswith("-*.png"):
            stem = png[: -len("-*.png")]
            src = stem  # a directory of frames under svg/modern/
            animated = True
        else:
            src = png[: -len(".png")]
            animated = False

        svg_path = svg_dir / (src if animated else f"{src}.svg")
        if not svg_path.exists():
            print(f"warning: no SVG for {name} ({svg_path})", file=sys.stderr)
            continue

        hot_x = cur.get("x_hotspot", fb_x) / CANVAS
        hot_y = cur.get("y_hotspot", fb_y) / CANVAS
        overrides = [name, *cur.get("x11_symlinks", [])]
        # de-dupe, preserve order
        seen = set()
        overrides = [o for o in overrides if not (o in seen or seen.add(o))]

        shapes.append(
            {
                "name": name,
                "source": src,
                "animated": animated,
                "hotspot_x": round(hot_x, 5),
                "hotspot_y": round(hot_y, 5),
                "delay": cur.get("x11_delay", fb_delay) if animated else 0,
                "overrides": overrides,
            }
        )

    for s in shapes:
        out.append(f"[[cursor]]")
        out.append(f'name = "{s["name"]}"')
        out.append(f'source = "{s["source"]}"')
        out.append(f"animated = {str(s['animated']).lower()}")
        out.append(f"hotspot_x = {s['hotspot_x']}")
        out.append(f"hotspot_y = {s['hotspot_y']}")
        if s["animated"]:
            out.append(f"delay = {s['delay']}")
        ov = ", ".join(f'"{o}"' for o in s["overrides"])
        out.append(f"overrides = [{ov}]")
        out.append("")

    sys.stdout.write("\n".join(out))
    print(f"\n# {len(shapes)} shapes", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
